### ISSUE TITLE
Unable to add nested elements

### ISSUE THREAD

**Issue by etherbob** [marijnh/crelt#1]
My apologies if I've misread the docs, but I would expect `crel('p', {}, ['strong', {}, 'hello'])` to return `<p><strong>hello</strong></p>` similar to prosemirror's toDOM spec. Instead I get `RangeError: Unsupported child node: [object Object]`.

**Comment by marijnh** [comment]
That's not how the library works. You want `[crel("strong", "hello")]`, not the arguments as an array.

**Comment by etherbob** [comment]
I figured that part out, but the docs and my prior use of Prosemirror seemed to imply the above could work as well. Thank you for clarifying. Would you be open to a Read Me PR if I can think of a decent one?

**Comment by marijnh** [comment]
The readme states that for array arguments, each element is added separately. I don't think that implies that you can do what you're doing above.

**Comment by etherbob** [comment]
That was actually the part that made me think that crel would operate on arrays like nested arguments, but I appreciate that it was my misunderstanding. I very much enjoy this sublimely lightweight, useful tool.
